#!/bin/sh

export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export HOME=$(mktemp -d)
trap "rm -rf ${HOME}" EXIT

xvfb-run -a --server-args="-screen 0 1024x768x24" \
    dbus-launch --exit-with-session debian/tests/testsuite.xsession
